debianization updated

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -4,63 +4,70 @@
 # Uncomment this to turn on verbose mode.
 export DH_VERBOSE=1
 
-UPVER := $(shell dpkg-parsechangelog | grep ^Version | cut -d' ' -f2 | cut -d- -f1 | cut -d+ -f1)
-TARNAME := mapnik_$(UPVER)+ds1.orig.tar
-
 # scons flags
-SCONS_FLAGS := INPUT_PLUGINS=gdal,geos,kismet,ogr,osm,postgis,raster,rasterlite,shape,sqlite
-SCONS_FLAGS += PROJ_INCLUDES=/usr/include PROJ_LIBS=/usr/lib
-SCONS_FLAGS += SYSTEM_FONTS=/usr/share/fonts/truetype/ttf-dejavu
-SCONS_FLAGS += XMLPARSER=libxml2
-SCONS_FLAGS += PREFIX=/usr LIB_DIR_NAME=/mapnik/2.0
+SCONS_FLAGS=INPUT_PLUGINS=csv,gdal,geojson,topojson,ogr,osm,postgis,raster,shape,sqlite \
+CXX=/opt/szn/bin/g++-4.8 \
+CC=/opt/szn/bin/gcc-4.8 \
+CUSTOM_CXXFLAGS="-fvisibility-inlines-hidden -fvisibility=hidden" \
+CAIRO=True \
+COLOR_PRINT=False \
+DEMO=True \
+SVG_RENDERER = True \
+PGSQL2SQLITE = True \
+SYSTEM_FONTS=/usr/share/fonts/truetype \
+DESTDIR=$(CURDIR)/debian/tmp PREFIX=/usr
+
+CFLAGS = -g
+
+ifneq (,$(findstring noopt,$(DEB_BUILD_OPTIONS)))
+	export CFLAGS += -O0
+else
+	export CFLAGS += -O3
+endif
+
+ifeq (,$(findstring nocheck,$(DEB_BUILD_OPTIONS)))
+override_dh_auto_test:
+else:
+override_dh_auto_test:
+	# the test suite does not 100% pass on all platforms/boost versions,
+	# but the output is useful :)
+	#make test-local || true; echo "Overall Test Exit Code: $?"
+endif
 
 override_dh_auto_configure:
-	scons $(SCONS_FLAGS) \
-		CCFLAGS="$(CFLAGS)" \
-		configure JOBS=20
+	./configure $(SCONS_FLAGS) CUSTOM_CXXFLAGS="$(CFLAGS)"
+	dh_auto_configure
 
-override_dh_auto_build:
-	set -e; \
-	for ver in $(shell pyversions -r -v); do \
-		scons $(SCONS_FLAGS) \
-			PYTHON=/usr/bin/python$$ver ; \
-	done
+# Do no build for every possible python version until this is working properly
+# https://github.com/mapnik/mapnik-packaging/issues/3
+#override_dh_auto_build:
+#	set -e; \
+#	for PYVER in $(shell pyversions -r); do \
+#		./configure \
+#		BOOST_PYTHON_LIB=`echo $$PYVER | sed 's/python\([0-9]\).\([0-9]\)/boost_python-py\1\2/'` \
+#		PYTHON=`which $$PYVER`; \
+#	done
+#
+#	dh_auto_build
 
 override_dh_prep:
 	dh_prep -Xdebian/tmp
 
-override_dh_auto_install:
-	for ver in $(shell pyversions -r -v); do \
-		scons $(SCONS_FLAGS) \
-			CCFLAGS="$(CFLAGS)" \
-			PYTHON=/usr/bin/python$$ver \
-			DESTDIR=$(CURDIR)/debian/tmp \
-			install ; \
-	done
+override_dh_install:
+	JOBS=2 make install
+	dh_install
 
 override_dh_auto_clean:
-	scons --clean $(SCONS_FLAGS)
-	find -name '*.pyc' -exec rm -f {} \;
-	find -name '.sconsign*' -exec rm -f {} \;
-	find -name '*.o' -exec rm -f {} \;
-	rm -rf .sconf_temp config.log bindings/python/mapnik/paths.py \
-		utils/shapeindex/shapeindex config.py config.cache \
-		docs/api_docs/python/*
-	dh_auto_clean
+	-make distclean
+	rm -rf config.py.backup
+
+#	dh_auto_clean
 
 override_dh_installexamples:
 	dh_installexamples -Xdata/new
 	find $(CURDIR)/debian/ -name "*.png" | xargs -r chmod -x
 
-override_dh_auto_test:
-	echo "Skipping tests"
-
-override_dh_installdocs:
-	echo "Skipping installdocs"
-
-#override_dh_shlibdeps:
-#	dh_shlibdeps --exclude=_mapnik.so	# zavisi na libmapnik.so.2.1, ktery se prave buildnul a tudiz neni ve std. cestach a balicich, zatim nevim jak to preprat jinak
-
 %:
-	dh $@ \
-		--with python2
+#	dh_installexamples -Xdata/new
+#	dh_install --sourcedir=debian/tmp
+	dh $@
